#!/usr/bin/env python3
"""
Auto-sync data/blocked-dates.json from Airbnb, Booking.com, and the
"Naz's Farm House Bookings" Google Calendar (used for WhatsApp/phone
confirmed bookings).

Run by .github/workflows/sync-calendar.yml on a schedule. Reads three
iCal feed URLs from environment variables (populated from GitHub repo
secrets — never hardcode the URLs here, they're private links), merges
every blocked night into one sorted list, and overwrites
data/blocked-dates.json.

Any source whose env var isn't set yet is skipped with a warning rather
than failing the whole run, so this works even before all three sources
are wired up.
"""
import json
import os
import re
import sys
import urllib.request
from datetime import date, timedelta

SOURCES = {
    "airbnb": os.environ.get("AIRBNB_ICAL_URL", "").strip(),
    "bookings_calendar": os.environ.get("BOOKINGS_ICAL_URL", "").strip(),
    "booking_com": os.environ.get("BOOKINGCOM_ICAL_URL", "").strip(),
}

OUTPUT_PATH = "data/blocked-dates.json"

DATE_FIELD_RE = re.compile(r"(DTSTART|DTEND)(;[^:\r\n]*)?:(\d{8})")


def fetch_ics(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "nazsfarmhouse-calendar-sync/1.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read().decode("utf-8", errors="replace")


def parse_date(raw: str) -> date:
    return date(int(raw[0:4]), int(raw[4:6]), int(raw[6:8]))


def parse_events(ics_text: str):
    """Return a list of (start_date, checkout_date) tuples from an ICS feed.

    checkout_date follows the standard iCal convention: DTEND is exclusive,
    so the last occupied night is checkout_date - 1 day.
    """
    events = []
    for block in ics_text.split("BEGIN:VEVENT")[1:]:
        block = block.split("END:VEVENT")[0]
        found = {}
        for m in DATE_FIELD_RE.finditer(block):
            found[m.group(1)] = parse_date(m.group(3))
        start = found.get("DTSTART")
        end = found.get("DTEND")
        if start and end:
            events.append((start, end))
        elif start:
            # No DTEND — treat as a single-night block.
            events.append((start, start + timedelta(days=1)))
    return events


def nights_between(start: date, checkout: date):
    d = start
    while d < checkout:
        yield d.isoformat()
        d += timedelta(days=1)


def main():
    all_nights = set()
    any_source_configured = False

    for name, url in SOURCES.items():
        if not url:
            print(f"skip {name}: no URL configured (env var not set)")
            continue
        any_source_configured = True
        try:
            ics_text = fetch_ics(url)
            events = parse_events(ics_text)
            for start, checkout in events:
                all_nights.update(nights_between(start, checkout))
            print(f"{name}: {len(events)} event(s) parsed")
        except Exception as exc:  # noqa: BLE001 - deliberately broad, one bad feed shouldn't kill the run
            print(f"WARNING: failed to fetch/parse {name}: {exc}", file=sys.stderr)

    if not any_source_configured:
        print("ERROR: no calendar source URLs are configured at all — check repo secrets.", file=sys.stderr)
        sys.exit(1)

    merged = sorted(all_nights)

    output = {
        "_comment": (
            "AUTO-GENERATED by .github/workflows/sync-calendar.yml — do not hand-edit, "
            "this file is overwritten on every scheduled sync. Merges Airbnb + Booking.com "
            "+ the 'Naz's Farm House Bookings' Google Calendar (WhatsApp/phone confirmed "
            "bookings go there manually, then flow through here automatically)."
        ),
        "_lastSynced": date.today().isoformat(),
        "blockedDates": merged,
    }

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
        f.write("\n")

    print(f"Wrote {len(merged)} blocked night(s) to {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
